print("This is FIRST project from PC")
print("NEW LINE This is FIRST project from PC")
print("SECOND NEW LINE This is FIRST project from PC")
print("ThIRD NEW LINE This is FIRST project from PC")
print("Fourth NEW LINE This is FIRST project from PC")